### ISSUE TITLE
LinTo always responds "I don't know" when I try to call my skill

### ISSUE THREAD

**Issue by DreyLyp** [linto-ai/linto-platform-business-logic-server#7]
Hello,

I have a problem with the skill, LinTo will always return to me "I do not know what to do", so I tried with the template and again he does not know.

However I see that the NLU managed to find which skill it corresponded to:

![image](https://user-images.githubusercontent.com/84905079/120647176-9896b580-c47a-11eb-93d7-2aabe8204f5b.png)

![image](https://user-images.githubusercontent.com/84905079/120647117-89b00300-c47a-11eb-8ceb-20d516a4e602.png)

If the template also doesn't work I deduce that it doesn't come from my skill but then where?

I nevertheless created the intents that should launch my skill I nevertheless created the intents that should launch my skill and the event file does have the same name as my intents:

![image](https://user-images.githubusercontent.com/84905079/120647657-22df1980-c47b-11eb-9f92-e7dd20f1a341.png)

![image](https://user-images.githubusercontent.com/84905079/120647752-3ab69d80-c47b-11eb-9ecc-c57382c43a12.png)

With regards,

**Comment by Houpert** [comment]
Hello,

Make sure that ouestfrance is on the folder events. (make sure that the skill is well update)
Also `package/events` feels odd to me, this workaround might generate a problems.

Also follow [make my skill](https://doc.linto.ai/#/skills/devguide/make_my_skills?id=introduction) to see if you don't have make any mistake.

The default intent on the template is `myEvent`. The template skill is just a template to help to structure / guide the user, not an usable skill.

Would it be possible to have a mail to contact you for making a call ? It would be easier.

Best regards

**Comment by DreyLyp** [comment]
Hello,

ouestfrance is in the folder events, for me too it seems strange to me but I only found this technique for my skill to be displayed on the admin interface.

However, I followed the guide well and despite this I have this problem.

No problem here is my email: dimitri.delpech@altervoice.fr

With regards

**Comment by Houpert** [comment]
Hello,

Problem solve, it was an error on the skill.

For future user : [skill information](https://doc.linto.ai/#/skills/devguide/make_my_skills?id=make-my-skill)

Best regards
